### ISSUE TITLE
为什么赋值两次？

### ISSUE THREAD

**Issue by zhuoyikang** [sniperHW/chuck#1]
void stream_socket_init(stream_socket_ *s,int32_t fd)
{
    s->on_events = on_events;     ---->
    s->imp_engine_add = imp_engine_add; ---->
    s->type = STREAM;
    s->fd = fd;
    s->on_events = on_events; ----> 又来一次。
    s->imp_engine_add = imp_engine_add; ---->
    s->status = SOCKET_READABLE | SOCKET_WRITEABLE;
    easy_close_on_exec(fd);
}

**Comment by sniperHW** [comment]
多copy了一次
