### ISSUE TITLE
有没有什么工具能统一排版。。

### ISSUE THREAD

**Issue by zhuoyikang** [sniperHW/chuck#2]
![image](https://cloud.githubusercontent.com/assets/2211585/9426397/65f8b0f0-4970-11e5-9773-1e2cb57ff2af.png)

![image](https://cloud.githubusercontent.com/assets/2211585/9426399/6c4c36ac-4970-11e5-853d-39b84550f64e.png)

**Comment by sniperHW** [comment]
vim本身就可以,我用sublime所以看不到这些字符
